# Allow local connections
local   all             all                                     trust
# Allow app connections to standby as needed
host    all             all             0.0.0.0/0               md5
# Allow replica connection from primary
host    replication     replicator      0.0.0.0/0               md5
