# Primary settings for streaming replication
listen_addresses = '*'
port = 5432
wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
wal_keep_size = 64
hot_standby = on
logging_collector = on
log_destination = 'stderr'
log_min_messages = notice
log_directory = 'log'
log_filename = 'postgresql-%a.log'
